### ISSUE TITLE
CST assignments required by Valody

### ISSUE THREAD

**Issue by qunfengdong** [ctmrbio/valody#3]
I read your paper with great interest: Hugerth, L.W., Krog, M.C., Vomstein, K. et al. Defining Vaginal Community Dynamics: daily microbiome transitions, the role of menstruation, bacteriophages, and bacterial genes. Microbiome 12, 153 (2024). https://doi.org/10.1186/s40168-024-01870-5
 
I am also grateful for the supplementary data you have provided.  I am wondering if you can also provide the assigned CST types for each sample listed in the Supplementary Table S1 and Supplementary Table S2.   I just couldn’t find any CST information for each of your samples, or maybe I have missed something.   

I hope to use the CST data to learn Valody (e.g., reproduce the results in your paper). 

Thanks for your help.

**Comment by luhugerth** [comment]
Hi, great comment! I have added the CST information in a new folder in this repo, called "Hugerth Krog files". Should be everything you need!

Commit history: https://github.com/ctmrbio/valody/commit/9b3fd8bf1048d9502e71afe90b44a1c33f6bb9a5
